### ISSUE TITLE
Publish an initial release on npm

### ISSUE THREAD

**Issue by ddbeck** [mdn/short-descriptions#21]
During this sprint, we should publish a release of mdn-short-descriptions on npm. It should contain all the CSS property descriptions in the repo to date and it should work a bit like the release process for browser-compat-data.

**Comment by ddbeck** [comment]
@wbamberg just a heads up: I plan to run our npm publishing workflow on Monday, with whatever descriptions we've got, in hopes of actually satisfying this sprint goal.

**Comment by ddbeck** [comment]
[It's published](https://www.npmjs.com/package/mdn-short-descriptions). Hooray! 🎉

**Comment by wbamberg** [comment]
Very nice work, Daniel!
